[package]
name = "my-great-rpg"
version = "0.1.3"
authors = ["Lemonzyy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordinal = "0.2.3"
crossterm = "0.18.2"
rand = "0.8.0"